# Generated by Django 3.1.6 on 2021-02-08 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spareparts', '0002_auto_20210208_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='local_comparison_sparepart',
            name='sp_type',
            field=models.CharField(choices=[('Ground Engaging Tools', 'Ground Engaging Tools'), ('Manganese Liners', 'Manganese Liners'), ('Mechanical Parts', 'Mechanical Parts')], default='mechanical parts', max_length=50),
        ),
    ]
