# Generated by Django 3.1.6 on 2021-02-11 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spareparts', '0003_auto_20210208_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='local_comparison_sparepart',
            name='part_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparison_sparepart', to='spareparts.sparepart', unique=True),
        ),
    ]
