# Generated by Django 3.1.6 on 2021-02-12 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spareparts', '0005_auto_20210212_0403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sparepart',
            name='sp_type',
            field=models.CharField(choices=[('Ground Engaging Tools', 'Ground Engaging Tools'), ('Manganese Liners', 'Manganese Liners'), ('Mechanical Parts', 'Mechanical Parts')], default='mechanical parts', max_length=50),
        ),
    ]
