export const FETCH_SITE_ORDER_START = 'FETCH_SITE_ORDER_START';
export const FETCH_SITE_ORDER_SUCCESS = 'FETCH_SITE_ORDER_SUCCESS';
export const FETCH_SITE_ORDER_FAILURE = 'FETCH_SITE_ORDER_FAILURE';


export const ADD_SITE_ORDER_START = 'ADD_SITE_ORDER_START';
export const ADD_SITE_ORDER_FAILURE = 'ADD_SITE_ORDER_FAILURE';

export const DEL_SITE_ORDER_START = 'DEL_SITE_ORDER_START';
export const DEL_SITE_ORDER_FAILURE = 'DEL_SITE_ORDER_FAILURE';


export const EDIT_SITE_ORDER_START = 'EDIT_SITE_ORDER_START';
export const EDIT_SITE_ORDER_FAILURE = 'EDIT_SITE_ORDER_FAILURE';