export const FETCH_SITE_START = 'FETCH_SITE_START';
export const FETCH_SITE_SUCCESS = 'FETCH_SITE_SUCCESS';
export const FETCH_SITE_FAILURE = 'FETCH_SITE_FAILURE';


export const ADD_SITE_START = 'ADD_SITE_START';
export const ADD_SITE_FAILURE = 'ADD_SITE_FAILURE';

export const DEL_SITE_START = 'DEL_SITE_START';
export const DEL_SITE_FAILURE = 'DEL_SITE_FAILURE';


export const EDIT_SITE_START = 'EDIT_SITE_START';
export const EDIT_SITE_FAILURE = 'EDIT_SITE_FAILURE';