export const FETCH_LOCALSPARE_START = 'FETCH_LOCALSPARE_START';
export const FETCH_LOCALSPARE_SUCCESS = 'FETCH_LOCALSPARE_SUCCESS';
export const FETCH_LOCALSPARE_FAILURE = 'FETCH_LOCALSPARE_FAILURE';


export const ADD_LOCALSPARE_START = 'ADD_LOCALSPARE_START';
export const ADD_LOCALSPARE_FAILURE = 'ADD_LOCALSPARE_FAILURE';

export const DEL_LOCALSPARE_START = 'DEL_LOCALSPARE_START';
export const DEL_LOCALSPARE_FAILURE = 'DEL_LOCALSPARE_FAILURE';


export const EDIT_LOCALSPARE_START = 'EDIT_LOCALSPARE_START';
export const EDIT_LOCALSPARE_FAILURE = 'EDIT_LOCALSPARE_FAILURE';