export const FETCH_MAIN_ORDER_START = 'FETCH_MAIN_ORDER_START';
export const FETCH_MAIN_ORDER_SUCCESS = 'FETCH_MAIN_ORDER_SUCCESS';
export const FETCH_MAIN_ORDER_FAILURE = 'FETCH_MAIN_ORDER_FAILURE';

export const FETCH_MONTHLY_ORDER_START = 'FETCH_MONTHLY_ORDER_START';
export const FETCH_MONTHLY_ORDER_SUCCESS = 'FETCH_MONTHLY_ORDER_SUCCESS';
export const FETCH_MONTHLY_ORDER_FAILURE = 'FETCH_MONTHLY_ORDER_FAILURE';

export const ADD_MAIN_ORDER_START = 'ADD_MAIN_ORDER_START';
export const ADD_MAIN_ORDER_FAILURE = 'ADD_MAIN_ORDER_FAILURE';

export const DEL_MAIN_ORDER_START = 'DEL_MAIN_ORDER_START';
export const DEL_MAIN_ORDER_FAILURE = 'DEL_MAIN_ORDER_FAILURE';


export const EDIT_MAIN_ORDER_START = 'EDIT_MAIN_ORDER_START';
export const EDIT_MAIN_ORDER_FAILURE = 'EDIT_MAIN_ORDER_FAILURE';