export const FETCH_SPAREPART_ML_START = 'FETCH_SPAREPART_ML_START';
export const FETCH_SPAREPART_ML_SUCCESS = 'FETCH_SPAREPART_ML_SUCCESS';
export const FETCH_SPAREPART_ML_FAILURE = 'FETCH_SPAREPART_ML_FAILURE';

export const FETCH_SPAREPART_MP_START = 'FETCH_SPAREPART_MP_START';
export const FETCH_SPAREPART_MP_SUCCESS = 'FETCH_SPAREPART_MP_SUCCESS';
export const FETCH_SPAREPART_MP_FAILURE = 'FETCH_SPAREPART_MP_FAILURE';

export const FETCH_SPAREPART_GET_START = 'FETCH_SPAREPART_GET_START';
export const FETCH_SPAREPART_GET_SUCCESS = 'FETCH_SPAREPART_GET_SUCCESS';
export const FETCH_SPAREPART_GET_FAILURE = 'FETCH_SPAREPART_GET_FAILURE';
