# Generated by Django 3.1.6 on 2021-02-08 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_request', '0002_auto_20210207_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainpurchaserequest',
            name='site_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sitespurchaserequest',
            name='site_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
