export const FETCH_SPAREPART_START = 'FETCH_SPAREPART_START';
export const FETCH_SPAREPART_SUCCESS = 'FETCH_SPAREPART_SUCCESS';
export const FETCH_SPAREPART_FAILURE = 'FETCH_SPAREPART_FAILURE';


export const ADD_SPAREPART_START = 'ADD_SPAREPART_START';
export const ADD_SPAREPART_FAILURE = 'ADD_SPAREPART_FAILURE';

export const DEL_SPAREPART_START = 'DEL_SPAREPART_START';
export const DEL_SPAREPART_FAILURE = 'DEL_SPAREPART_FAILURE';


export const EDIT_SPAREPART_START = 'EDIT_SPAREPART_START';
export const EDIT_SPAREPART_FAILURE = 'EDIT_SPAREPART_FAILURE';




export const FETCH_SPAREPARTFULL_START = 'FETCH_SPAREPARTFULL_START';
export const FETCH_SPAREPARTFULL_SUCCESS = 'FETCH_SPAREPARTFULL_SUCCESS';
export const FETCH_SPAREPARTFULL_FAILURE = 'FETCH_SPAREPARTFULL_FAILURE';