# Generated by Django 3.1.6 on 2021-02-07 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='state',
            field=models.CharField(choices=[('ACT', 'ACT'), ('QLD', 'QLD'), ('NSW', 'NSW'), ('SA', 'SA'), ('VIC', 'VIC'), ('TAS', 'TAS'), ('NT', 'NT'), ('WA', 'WA')], default='VIC', max_length=10),
        ),
    ]
