export const FETCH_ROLLER_START = 'FETCH_ROLLER_START';
export const FETCH_ROLLER_SUCCESS = 'FETCH_ROLLER_SUCCESS';
export const FETCH_ROLLER_FAILURE = 'FETCH_ROLLER_FAILURE';


export const ADD_ROLLER_START = 'ADD_ROLLER_START';
export const ADD_ROLLER_FAILURE = 'ADD_ROLLER_FAILURE';

export const DEL_ROLLER_START = 'DEL_ROLLER_START';
export const DEL_ROLLER_FAILURE = 'DEL_ROLLER_FAILURE';


export const EDIT_ROLLER_START = 'EDIT_ROLLER_START';
export const EDIT_ROLLER_FAILURE = 'EDIT_ROLLER_FAILURE';